// Compiled shader for Windows, Mac, Linux

//////////////////////////////////////////////////////////////////////////
// 
// NOTE: This is *not* a valid shader file, the contents are provided just
// for information and for debugging purposes only.
// 
//////////////////////////////////////////////////////////////////////////
// Skipping shader variants that would not be included into build of current scene.

Shader "Sprites/JiggleSprite" {
Properties {
[PerRendererData]  _MainTex ("Sprite Texture", 2D) = "white" { }
 _MaskTex ("Jiggle Mask (R=Bounce, G=Wave, B=Noise, A=Intensity)", 2D) = "white" { }
 _Color ("Tint", Vector) = (1.000000,1.000000,1.000000,1.000000)
[Header(Bounce Jiggle (Red Channel))]  _JiggleSpeed ("Bounce Speed", Float) = 1.000000
 _JiggleStrength ("Bounce Strength", Float) = 0.050000
[Header(Wave Jiggle (Green Channel))]  _JiggleFrequency ("Wave Frequency", Float) = 10.000000
[Header(Noise Jiggle (Blue Channel))]  _NoiseScale ("Noise Scale", Float) = 20.000000
 _NoiseSpeed ("Noise Speed", Float) = 0.500000
 _NoiseStrength ("Noise Strength", Float) = 0.030000
[Header(Rendering)] [Toggle]  _PixelSnap ("Pixel Snap", Float) = 0.000000
[HideInInspector]  _RendererColor ("RendererColor", Vector) = (1.000000,1.000000,1.000000,1.000000)
[HideInInspector]  _Flip ("Flip", Vector) = (1.000000,1.000000,1.000000,1.000000)
}
SubShader { 
 LOD 200
 Tags { "RenderType"="Opaque" }


 // Stats for Vertex shader:
 //        d3d11: 9 math
 // Stats for Fragment shader:
 //        d3d11: 1 math, 1 texture
 Pass {
  Tags { "RenderType"="Opaque" }
  //////////////////////////////////
  //                              //
  //      Compiled programs       //
  //                              //
  //////////////////////////////////
//////////////////////////////////////////////////////
Keywords: <none>
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 9 math, 2 temp registers
Uses vertex data channel "Vertex"
Uses vertex data channel "TexCoord0"

Constant Buffer "$Globals" (160 bytes) on slot 0 {
  Matrix4x4 unity_ObjectToWorld at 0
  Matrix4x4 unity_MatrixVP at 64
  Vector4 _MainTex_ST at 128
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xy          0     NONE   float   xy  
// SV_POSITION              0   xyzw        1      POS   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[9], immediateIndexed
      dcl_input v0.xyzw
      dcl_input v1.xy
      dcl_output o0.xy
      dcl_output_siv o1.xyzw, position
      dcl_temps 2
   0: mad o0.xy, v1.xyxx, cb0[8].xyxx, cb0[8].zwzz
   1: mul r0.xyzw, v0.yyyy, cb0[1].xyzw
   2: mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
   3: mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
   4: mad r0.xyzw, cb0[3].xyzw, v0.wwww, r0.xyzw
   5: mul r1.xyzw, r0.yyyy, cb0[5].xyzw
   6: mad r1.xyzw, cb0[4].xyzw, r0.xxxx, r1.xyzw
   7: mad r1.xyzw, cb0[6].xyzw, r0.zzzz, r1.xyzw
   8: mad o1.xyzw, cb0[7].xyzw, r0.wwww, r1.xyzw
   9: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
// Stats: 1 math, 1 temp registers, 1 textures
Set 2D Texture "_MainTex" to slot 0

Constant Buffer "$Globals" (160 bytes) on slot 0 {
  Vector4 _Color at 144
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xy          0     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_constantbuffer CB0[10], immediateIndexed
      dcl_sampler s0, mode_default
      dcl_resource_texture2d (float,float,float,float) t0
      dcl_input_ps linear v0.xy
      dcl_output o0.xyzw
      dcl_temps 1
   0: sample r0.xyzw, v0.xyxx, t0.xyzw, s0
   1: mul o0.xyzw, r0.xyzw, cb0[9].xyzw
   2: ret 
// Approximately 0 instruction slots used


 }
}
Fallback "Sprites/Default"
}